#player
Olive oil...
#player
Red pesto...
#player
Salt...
#player
Pepper...
#player
Yep. It's all there. Everything you need for the best possible dinner.
#disable_script
#player
Can't wait to get home tonight...